### ISSUE TITLE
Unable to access website or use CLI of Malboost

### ISSUE THREAD

**Issue by Rohit-Satyam** [roelof89/malboost#1]
Hi @roelof89 

I was trying to use Malboost webserver but it failed to load. Besides, while using CLI, I get the following error:

```
./launch.sh
667798:C 02 Jan 2024 15:34:59.512 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
667798:C 02 Jan 2024 15:34:59.512 # Redis version=5.0.3, bits=64, commit=00000000, modified=0, pid=667798, just started
667798:C 02 Jan 2024 15:34:59.512 # Configuration loaded
667798:M 02 Jan 2024 15:34:59.514 * Increased maximum number of open files to 10032 (it was originally set to 1024).
667798:M 02 Jan 2024 15:34:59.520 # Not listening to IPv6: unsupproted
                _._                                                  
           _.-``__ ''-._                                             
      _.-``    `.  `_.  ''-._           Redis 5.0.3 (00000000/0) 64 bit
  .-`` .-```.  ```\/    _.,_ ''-._                                   
 (    '      ,       .-`  | `,    )     Running in standalone mode
 |`-._`-...-` __...-.``-._|'` _.-'|     Port: 6380
 |    `-._   `._    /     _.-'    |     PID: 667798
  `-._    `-._  `-./  _.-'    _.-'                                   
 |`-._`-._    `-.__.-'    _.-'_.-'|                                  
 |    `-._`-._        _.-'_.-'    |           http://redis.io        
  `-._    `-._`-.__.-'_.-'    _.-'                                   
 |`-._`-._    `-.__.-'    _.-'_.-'|                                  
 |    `-._`-._        _.-'_.-'    |                                  
  `-._    `-._`-.__.-'_.-'    _.-'                                   
      `-._    `-.__.-'    _.-'                                       
          `-._        _.-'                                           
              `-.__.-'                                               

667798:M 02 Jan 2024 15:34:59.521 # Server initialized
667798:M 02 Jan 2024 15:34:59.521 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
667798:M 02 Jan 2024 15:34:59.521 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
667798:M 02 Jan 2024 15:34:59.521 * Ready to accept connections
Usage: celery [OPTIONS] COMMAND [ARGS]...
Try 'celery --help' for help.

Error: Invalid value for '-A' / '--app': 
Unable to load celery application.
While trying to load the module app.celery the following error occurred:
Traceback (most recent call last):
  File "/home/subudhak/miniconda3/envs/malboost/lib/python3.12/site-packages/celery/bin/celery.py", line 58, in convert
    return find_app(value)
           ^^^^^^^^^^^^^^^
  File "/home/subudhak/miniconda3/envs/malboost/lib/python3.12/site-packages/celery/app/utils.py", line 383, in find_app
    sym = symbol_by_name(app, imp=imp)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/subudhak/miniconda3/envs/malboost/lib/python3.12/site-packages/kombu/utils/imports.py", line 59, in symbol_by_name
    module = imp(module_name, package=package, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/subudhak/miniconda3/envs/malboost/lib/python3.12/site-packages/celery/utils/imports.py", line 109, in import_from_cwd
    return imp(module, package=package)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/subudhak/miniconda3/envs/malboost/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 994, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/data/tools/malboost/app.py", line 27, in <module>
    from model import model_execute
  File "/data/tools/malboost/model.py", line 13, in <module>
    db_con = create_engine(os.getenv('SQLALCHEMY_DATABASE_URI'))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 2, in create_engine
  File "/home/subudhak/miniconda3/envs/malboost/lib/python3.12/site-packages/sqlalchemy/util/deprecations.py", line 281, in warned
    return fn(*args, **kwargs)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^
  File "/home/subudhak/miniconda3/envs/malboost/lib/python3.12/site-packages/sqlalchemy/engine/create.py", line 548, in create_engine
    u = _url.make_url(url)
        ^^^^^^^^^^^^^^^^^^
  File "/home/subudhak/miniconda3/envs/malboost/lib/python3.12/site-packages/sqlalchemy/engine/url.py", line 843, in make_url
    raise exc.ArgumentError(
sqlalchemy.exc.ArgumentError: Expected string or URL object, got None
```

You mention in the readme that we need to provide some database files but it's unclear where I get this `'sqlite:///data/YOURDATABASE.db'` file from! The steps I used to create a conda environment are as follows:

```
conda create -n malboost python
conda activate malboost
mamba install -c anaconda redis
mamba install -c conda-forge -c bioconda apscheduler werkzeug jinja2 arboreto flask-mail celery flask-sqlalchemy flask_cors python-dotenv
```

**Comment by roelof89** [comment]
This service is no longer running. I am no longer affiliated with the University anymore. So they stopped the service.

Seems like in the ./launch.sh the celery command no longer uses "-A app.celery" but "-A app".

Maybe that should be enough to make it work. I am not maintaining this code anymore. So some stuff may just require new updates.

If you use "pip install -r requirements.txt" you should be running the correct versions of the packages.  Your condo install will go for version much later than this app.

**Comment by Rohit-Satyam** [comment]
Hi @roelof89. Thanks for your suggestion. replacing `-A app.celery` to  `-A celery` helped and the error disappeared and now I get the following message:

```
679741:C 03 Jan 2024 02:21:01.258 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
679741:C 03 Jan 2024 02:21:01.258 # Redis version=5.0.3, bits=64, commit=00000000, modified=0, pid=679741, just started
679741:C 03 Jan 2024 02:21:01.258 # Configuration loaded
679741:M 03 Jan 2024 02:21:01.259 * Increased maximum number of open files to 10032 (it was originally set to 1024).
679741:M 03 Jan 2024 02:21:01.266 # Not listening to IPv6: unsupproted
679741:M 03 Jan 2024 02:21:01.266 # Could not create server TCP listening socket *:6380: bind: Address already in use
 
 -------------- celery@KW61216 v5.3.6 (emerald-rush)
--- ***** ----- 
-- ******* ---- Linux-5.4.0-166-generic-x86_64-with-glibc2.31 2024-01-03 02:21:04
- *** --- * --- 
- ** ---------- [config]
- ** ---------- .> app:         default:0x1510459df560 (.default.Loader)
- ** ---------- .> transport:   amqp://guest:**@localhost:5672//
- ** ---------- .> results:     disabled://
- *** --- * --- .> concurrency: 112 (solo)
-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
--- ***** ----- 
 -------------- [queues]
                .> celery           exchange=celery(direct) key=celery
                

[tasks]
  . celery.accumulate
  . celery.backend_cleanup
  . celery.chain
  . celery.chord
  . celery.chord_unlock
  . celery.chunks
  . celery.group
  . celery.map
  . celery.starmap
```
I tried installing the dependencies in the empty conda environment using `pip install -r requirements.txt` but it always ended in a strange error that I was not able to debug. The error is given below:

```
pip install -r requirements.txt
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
Collecting git+https://github.com/tmoerman/arboreto.git (from -r requirements.txt (line 6))
  Cloning https://github.com/tmoerman/arboreto.git to /tmp/pip-req-build-10llu7u1
  Running command git clone --filter=blob:none --quiet https://github.com/tmoerman/arboreto.git /tmp/pip-req-build-10llu7u1
  Resolved https://github.com/tmoerman/arboreto.git to commit 2f475dca08f47a60acc2beb8dd897e77b7495ca4
  Preparing metadata (setup.py) ... done
Collecting Flask_Mail==0.9.1 (from -r requirements.txt (line 1))
  Downloading Flask-Mail-0.9.1.tar.gz (45 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.7/45.7 kB 550.9 kB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting pandas==0.25.3 (from -r requirements.txt (line 2))
  Downloading pandas-0.25.3.tar.gz (12.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.6/12.6 MB 42.5 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [18 lines of output]
      /tmp/pip-install-w0u7plmr/pandas_4e518b68e0bb483b8c688273cfa8252e/setup.py:12: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
        import pkg_resources
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-w0u7plmr/pandas_4e518b68e0bb483b8c688273cfa8252e/setup.py", line 812, in <module>
          version=versioneer.get_version(),
                  ^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-install-w0u7plmr/pandas_4e518b68e0bb483b8c688273cfa8252e/versioneer.py", line 1440, in get_version
          return get_versions()["version"]
                 ^^^^^^^^^^^^^^
        File "/tmp/pip-install-w0u7plmr/pandas_4e518b68e0bb483b8c688273cfa8252e/versioneer.py", line 1369, in get_versions
          cfg = get_config_from_root(root)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-install-w0u7plmr/pandas_4e518b68e0bb483b8c688273cfa8252e/versioneer.py", line 401, in get_config_from_root
          parser = configparser.SafeConfigParser()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      AttributeError: module 'configparser' has no attribute 'SafeConfigParser'. Did you mean: 'RawConfigParser'?
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

```
Alas!! I am not as good at python as I am at R. The `./launch.sh` doesn't open any interactive window. But I understand that since you aren't part of your previous lab it isn't being maintained. Thanks anyway for your feedback. Will close this issue

**Comment by roelof89** [comment]
I've ran into similar issues now. Try using "pip install --upgrade pip" then install requirements. But I think the pandas version for this project is too old and not supported anymore. I'll try and see if I can find working dependencies.
